url: "http://leet.cloud"
#logo: "/img/alex.png"
formspreeemail: "info@leet.cloud"

maincolor: "#189cd7"
secondarydarkcolor: "#233140"
secondarylightcolor: "white"
dropdowncolor: "#11866f"

headertitle: "Alex Simpson"
title: Alex Simpson
blurb: "AWS cloud consultant, serverless fanatic and housebus enthusiast!"
CV: "Alex-simpson-CV.pdf"
portfoliofadecolor: "#189cd7" 
#these images should be 900x650px

blogheading: "My Blogs"
blogimg1: "/img/portfolio/cloud-portfolio2.png"
blogimg2: "/img/portfolio/LittleKiwiBus_Logo_scaled.png"

projectheading: "My Projects"
projectimg1: "/img/portfolio/puppie-900-650.png"
# projectimg2: "/img/portfolio/bridgedoctor.png"

aboutcolumn1: "With over 8 years industry experience, Alex is a passionate automation and public cloud expert who brings innovative and creative solutions to highly technical problems."
aboutcolumn2: "At the same time Alex and his partner Bridget are planning on converting a 1979 Ford R1114 bus into their dream tiny house/house-bus. Follow their journey below!"
certs:
  - name: "VCP6-DCV"
    imagepath: "/img/cert-badges/Telerik.Web.UI.WebResource.png"
  - name: "AWS-SA-A"
    imagepath: "/img/cert-badges/VMW-LGO-CERT-PRO-6-DATA-CTR-VIRT.png"
  - name: "AWS-DV-A"
    imagepath: "/img/cert-badges/developer-badge.png"
  - name: "AWS-SO-A"
    imagepath: "/img/cert-badges/sys-ops-badge.png" 
  - name: "AWS-AN-S"
    imagepath: "/img/cert-badges/advanced-networking-badge.png" 
  - name: "AWS-DO-P"
    imagepath: "/img/cert-badges/devops-pro-badge.png"
  - name: "AWS-SA-P"
    imagepath: "/img/cert-badges/architect-pro-badge.png"    
  - name: "GCP-DE-P"
    imagepath: "/img/cert-badges/google-certified-data-engineer.png"

address1: Brisbane
address2: Australia

facebook: "https://www.facebook.com/ajsimpson69"
stackoverflow: "http://stackoverflow.com/users/7040399/vendablefall"
twitter: "https://twitter.com/VendableFall"
linkedin: "https://www.linkedin.com/in/alexander-simpson-35716189/"
github: "https://github.com/vendablefall"

aboutfooter:
aboutfooterbody:
