url: "http://leet.cloud"
#logo: "/img/alex.png"
formspreeemail: "info@leet.cloud"

maincolor: "#189cd7"
secondarydarkcolor: "#233140"
secondarylightcolor: "white"
dropdowncolor: "#11866f"

headertitle: "Alex Simpson"
title: Alex Simpson
blurb: "Virtualisation Engineer's Journey into the Public Cloud"
CV: "Alex-simpson-CV.odt"
portfolioheading: "My Blogs"
portfoliofadecolor: "#189cd7" 
#these images should be 900x650px
portfolioimg1: "/img/portfolio/cloud-portfolio2.png"
portfolioimg2: "/img/portfolio/LittleKiwiBus_Logo_scaled.png"
portfolioimg3: 

aboutcolumn1: "With over 7 years industry experience, Alex is a passionate automation and public cloud expert who brings innovative and creative solutions to highly technical problems."
aboutcolumn2: "At the same time Alex and his partner Bridget are planning on converting an American school bus into their dream tiny house/house-bus. Follow their journey below!"
certs:
  - name: "VCP6-DCV"
    imagepath: "/img/cert-badges/Telerik.Web.UI.WebResource.png"
  - name: "AWS-SA-A"
    imagepath: "/img/cert-badges/VMW-LGO-CERT-PRO-6-DATA-CTR-VIRT.png"
  - name: "AWS-DV-A"
    imagepath: "/img/cert-badges/developer-badge.png"
  - name: "AWS-SO-A"
    imagepath: "/img/cert-badges/sys-ops-badge.png" 
  - name: "AWS-AN-S"
    imagepath: "/img/cert-badges/advanced-networking-badge.png" 
    
address1: Brisbane
address2: Australia

facebook: "https://www.facebook.com/ajsimpson69"
stackoverflow: "http://stackoverflow.com/users/7040399/vendablefall"
twitter: "https://twitter.com/VendableFall"
linkedin: "https://www.linkedin.com/in/alexander-simpson-35716189/"
github: "https://github.com/vendablefall"

aboutfooter:
aboutfooterbody:
